apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogIllYSnpaVzU1T0RBeU9tZHBkR2gxWWw5d1lYUmZNVEZCUmt0WFRWTlpNSEpvVTBWdVZHUnBjRU5pZWw4Mk9GaDRTa05JTVZKMVJsQmxPRFpwVWpGcVZqWjNWRVZZTVdsRlRqWnpOV0pEU1RsWGRYRTJSV2xQUjB0TE5qTlFVRXhIZFVOUWJ6Qk1aZz09IiwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiLAoJInBsdWdpbnMiOiB7CgkJIi14LWNsaS1oaW50cyI6IHsKCQkJImVuYWJsZWQiOiAidHJ1ZSIKCQl9LAoJCSJkZWJ1ZyI6IHsKCQkJImhvb2tzIjogImV4ZWMiCgkJfSwKCQkic2NvdXQiOiB7CgkJCSJob29rcyI6ICJwdWxsLGJ1aWxkeCBidWlsZCIKCQl9Cgl9LAoJImZlYXR1cmVzIjogewoJCSJob29rcyI6ICJ0cnVlIgoJfQp9
type: kubernetes.io/dockerconfigjson
