apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS50cmFzc2lyLmNvbTo2NDQzIjogewoJCQkiYXV0aCI6ICJZUzV5WVhacGJqcFdZVWR5UVc1VU1URTJOelU9IgoJCX0sCgkJImdoY3IuaW8iOiB7CgkJCSJhdXRoIjogIllYSnpaVzU1T0RBeU9tZHBkR2gxWWw5d1lYUmZNVEZCUmt0WFRWTlpNSEpvVTBWdVZHUnBjRU5pZWw4Mk9GaDRTa05JTVZKMVJsQmxPRFpwVWpGcVZqWjNWRVZZTVdsRlRqWnpOV0pEU1RsWGRYRTJSV2xQUjB0TE5qTlFVRXhIZFVOUWJ6Qk1aZz09IgoJCX0KCX0KfQo=
type: kubernetes.io/dockerconfigjson
